version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: qa-postgres
    environment:
      POSTGRES_DB: qa_dashboard
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: