services:
  postgres:
    image: postgres:15
    container_name: qa-postgres
    environment:
      POSTGRES_DB: qa_dashboard
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/init/02_apply_migrations.sql:/docker-entrypoint-initdb.d/02_apply_migrations.sql
      - ./database/migrations/005_add_tree_structure_to_test_cases.sql:/docker-entrypoint-initdb.d/03_tree_structure.sql
    restart: unless-stopped

volumes:
  postgres_data:
